### ISSUE TITLE
[Request] Recipe to turn back into regular pane

### ISSUE THREAD

**Issue by NillerMedDild** [MongoTheElder/PITG#1]
Hi!

I would like to suggest that you add a conversion recipe to turn PITG Panes back into regular ones, just in case someone crafts them by mistake or the like :)

**Comment by MongoTheElder** [comment]
Already implemented in 1.2.0 ;)
1.2.0 fixes the two known bugs (Glazing tool not rotating stained panes and the dev textures for clear panes), adds dual panes, and updates the crafting recipes.

**Comment by NillerMedDild** [comment]
My apologies, I thought I was on the latest, thanks!

**Comment by MongoTheElder** [comment]
No worries, I just released 1.2.0 yeaterday
