### ISSUE TITLE
[1.16.3] Server crashes on startup

### ISSUE THREAD

**Issue by NillerMedDild** [MongoTheElder/PITG#10]
Well, title :D

`pitg-1.16.3-1.4.0` 

https://gist.github.com/NillerMedDild/aee7340657bc3057dfb219ad67a4e8a0

**Comment by MongoTheElder** [comment]
Fixed the server startup but and uncovered another, even larger issue. Stay tuned...

The server startup problem was with the way I was registering the custom item property that changes the Glazing Tool item model based on it's state.

**Comment by MongoTheElder** [comment]
1.16.3-1.4.1 is in release review by CurseForge. It should fix the start up problem (tested on a couple server configurations)

**Comment by NillerMedDild** [comment]
Thank you kindly!

**Comment by MongoTheElder** [comment]
Please let me know if you have any other issues.
