### ISSUE TITLE
Feature request: Top/Bottom aligned glass

### ISSUE THREAD

**Issue by AkashaP** [MongoTheElder/PITG#14]
As per title. Found this mod floating around in Valhesia 3 and thought it would have been cool if the glass panes could align to the top and bottom of the blocks rather than just the sides.

**Comment by MongoTheElder** [comment]
That's been on the To Do list for a while. It would require a substantial refactoring of the mod and would break existing player builds. I've been looking at adding horizontal panes as an option but they wouldn't have the same integration into a single block space.

**Comment by MongoTheElder** [comment]
Horizontal Glass Panes are coming soon!

**Comment by MongoTheElder** [comment]
Horizontal panes are now available in versions from 1.18 onward
