### ISSUE TITLE
rain/particles not rendering through glass [1.16.4]

### ISSUE THREAD

**Issue by caligator** [MongoTheElder/PITG#16]
have this mod added to my Direwolf20 pack. noticed that rain doesnt render when viewed through the panes. normal panes it works fine. 

not sure if this is a bug or was a known limitation of the system.

**Comment by MongoTheElder** [comment]
This is an unusual behavior of Minecraft. When the render mode is set to 'cutout' (like vanilla clear glass), rain is rendered, if it is set to 'transparent' (like vanilla colored glass), it is not. I follow the same conventions as vanilla for rendering mode.
