### ISSUE TITLE
[1.19.2] Glass pane table does not drop as an item when mined with a pickaxe

### ISSUE THREAD

**Issue by 0DeltaWaves** [MongoTheElder/PITG#29]
Version: pitg-1.19.1-2.1.1
Mining with a pickaxe deletes the block, which does not seem like intentional design.

**Comment by MongoTheElder** [comment]
This is the same as vanilla behavior. Breaking a glass block or pane with a non silk touch tool doesn't drop the block.

**Comment by MongoTheElder** [comment]
I'll take a look. I may have left the old loot table in place.

**Comment by 0DeltaWaves** [comment]
I'm talking about the table you make the different kinds of panes in, not a glass block. I'd assume you would be able to pick it back up after placing?

**Comment by MongoTheElder** [comment]
During the "grand prune" for 1.19, I transitioned all the asset generation from hand created files to auto generated. I missed adding the loot table for the Glass Pane Table. 2.1.2 adds the correct generator.
