### ISSUE TITLE
Request for Stain Glass Like Designs

### ISSUE THREAD

**Issue by laurasharp** [MongoTheElder/PITG#31]
I really like some of the stain glass mods that are out there and had hoped that your mod would make those work like yours, but sadly they don't. 

The mod I am currently using is Macaw's Windows. Based on the other comments I am guessing it isn't possible to be compatible. 

So could you provide similar stain glass like options?

**Comment by MongoTheElder** [comment]
Unfortunately due to the nature of PITG, it's not possible to incorporate textures from other mods. The PITG textures need to be structured to support conditions that general glass pane textures don't implement.
